- name: Wipe out the application
  become: true
  block:
    - name: Stop and remove Docker container
      docker_container:
        name: "{{ docker_container_name }}"
        state: absent

    - name: Remove all unused Docker objects
      ansible.builtin.command:
        cmd: docker system prune -a -f
      become: true
      ignore_errors: true

    - name: Remove all unused Docker volumes
      ansible.builtin.command:
        cmd: docker volume prune -f
      become: true
      ignore_errors: true

    - name: Remove docker-compose file
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/docker-compose.yml"
        state: absent
  when: web_app_full_wipe
  tags:
    - wipe
