# docker-compose.yml
version: "3"

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - loki

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    depends_on:
      - promtail

  promtail:
    image: grafana/promtail:latest
    ports:
      - "9080:9080"
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./promtail-config/config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml

  app_javascript:
    build: ../app_javascript
    ports:
      - "5000:5000"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  app_python:
    build: ../app_python
    ports:
      - "5001:5000"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  grafana-data:
