- name: Add {{ ansible_user }} to the docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
  listen: start_docker

- name: Start docker service
  systemd:
    name: docker
    state: started
  listen: start_docker
